backend/models/AuthItem.php
<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use common\models\AuthMenuItem;
use common\models\User;

/**
 * El modelo AuthItem se refiere a los roles y permisos existentes en el sistema
 * 
 * Ejemplo:
 * r-admin es un AuthItem y representa el rol de administrador
 * 
 * @property string $name nombre
 * @property int $type tipo
 * @property string $description descripción
 * @property string $rule_name nombre regla asociada
 * @property string $data data
 * @property datetime $created_at creado el
 * @property datetime $updated_at actualizado el
 *
 * @property AuthAssignment[] $authAssignments lista objetos de tipo AuthAssignment
 * @property User[] $users lista de usuarios
 * @property AuthRule $ruleName la regla asociada
 * @property AuthItemChild[] $authItemChildren AuthItemChild hijos
 * @property AuthItemChild[] $authItemParents AuthItemChild padres
 * @property AuthMenuItem[] $authMenuItems AuthMenuItem asociados
 * 
 * @property string $tipoTexto nombre del tipo
 * 
 */
class AuthItem extends ActiveRecord {
    const TIPO_ROL = 1;
    const TIPO_ROL_TEXTO = 'Rol';
    const TIPO_PERMISO = 2;
    const TIPO_PERMISO_TEXTO = 'Permiso';
    
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'auth_item';
    }  
    
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
        ];        
    }    

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['name', 'type'], 'required'],
            [['name'], 'unique'],
            [['type', ], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['description', 'data'], 'string'],
            [['name', 'rule_name'], 'string', 'max' => 64]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'name' => 'Rol/Permiso',
            'type' => 'Tipo',
            'description' => 'Descripción',
            'rule_name' => 'Nombre regla asociada',
            'data' => 'Data',
            'created_at' => 'Creado el',
            'updated_at' => 'Actualizado el',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthAssignments() {
        return $this->hasMany(AuthAssignment::className(), ['item_name' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers() {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->viaTable('auth_assignment', ['item_name' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuleName() {
        return $this->hasOne(AuthRule::className(), ['name' => 'rule_name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren() {
        return $this->hasMany(AuthItemChild::className(), ['parent' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemParents() {
        return $this->hasMany(AuthItemChild::className(), ['child' => 'name']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthMenuItems() {
        return $this->hasMany(AuthMenuItem::className(), ['auth_item' => 'name']);
    }

    /**
     * @return string el tipo
     */
    public  function getTipoTexto() {
        $tipo = ($this->type == AuthItem::TIPO_ROL) 
                ? AuthItem::TIPO_ROL_TEXTO : AuthItem::TIPO_PERMISO_TEXTO; 
        return $tipo;
    } 
    
    /**
     * Crea un arreglo con la lista de todos los roles del sistema a excepción
     * del rol: r-super-admin el cuál, se debe agregar únicamente por base de datos
     * 
     * @return array lista de roles [id => descripcion]
     */
    public static function rolesNombreDescripcion() {
        $roles = Yii::$app->authManager->getRoles();
        $rolesArray = ArrayHelper::map($roles, 'name', 'description');
        ArrayHelper::remove($rolesArray, 'r-super-admin');
        
        return $rolesArray;
    } 

    
    /**
     * Crea un arreglo con el label según el tipo
     * 
     * @return array lista de label [id_tipo => label]
     */
    public static function arrayTipo() {
        return [
            self::TIPO_ROL => self::TIPO_ROL_TEXTO,
            self::TIPO_PERMISO => self::TIPO_PERMISO_TEXTO,
        ];
    } 
    
    /**
     * Lista los roles/permisos y subroles/subpermisos
     * 
     * @return array nodos con el análisis de roles/permisos
     */
    public static function arbolPermisos(){
        $todos = self::find()->orderBy(['type' => SORT_ASC, 'name' => SORT_ASC, ])->all();
        
        $nodos = [];
        foreach ($todos as $key => $permiso) {
            $nodos[] = self::analisisPermisos($permiso->name, "");
        }
        return $nodos;
    }

    /**
     * Recursión que permite obtener el árbol completo (padres e hijos) de los
     * roles/permisos
     * 
     * @param string $padre padre inicial
     * @param string $texto label de como se va a ver en el árbol
     * @return array si es hoja retorna un arreglo con el texto; si es una rama
     * retorna un arreglo con el texto y sus nodos hijos
     */
    public static function analisisPermisos($padre, $texto){
        $modeloPadre = self::find()->where('name = :name', [':name' => $padre])->one();
        $hijos = AuthItemChild::find()->where('parent = :padre', 
                [':padre' => $padre])->orderBy(['parent' => SORT_ASC, 'child' => SORT_ASC, ])->all();
        
        if($hijos){
            
            $nodos = [];
            foreach ($hijos as $key => $hijo) {
                $nodos[] = self::analisisPermisos($hijo->child, $texto);
            }
            
            return [ //rama 
                    'text' => "($modeloPadre->type) - [$modeloPadre->name]" , 
                    'nodes' => $nodos,
                ];           
                
        } else {
            return //hoja;
                [ 
                    'text' => "($modeloPadre->type) - [$modeloPadre->name]" , 
                ];
        }
    }        
    
    /**
     * Permite saber si un AuthItem se puede eliminar
     * 
     * @return boolean TRUE si se puede eliminar, FALSE de lo contrario
     */
    public function sePuedeEliminar() {
        if($this->authAssignments){
            return FALSE;
        }
        
        if($this->authItemChildren){
            return FALSE;
        }
        
        if($this->authItemParents){
            return FALSE;
        }
        
        if($this->authMenuItems){
            return FALSE;
        }
        
        return TRUE;    
    }
    
    /**
     * Objetos que están relacionados a través de otros objetos, modelos o tablas
     * que restringen el delete
     * 
     * @return string detalle de los objetos con los cuales está relacionado
     */
    public function objetosRelacionados() {
        $detalle = '';
        
        if($this->authAssignments){    
            $detalle .= 'Permisos vs. Usuarios: <ul>';
            foreach ($this->authAssignments as $authAssignment) {
                $detalle .= '<li>'.$authAssignment->user->nombresYApellidos.'</li>';
            }
            $detalle .= '</ul>';
        }
        
        if($this->authItemChildren){    
            $detalle .= 'Es padre de los roles/permisos: <ul>';
            foreach ($this->authItemChildren as $authItemChildren) {
                $detalle .= '<li>'.$authItemChildren->child.'</li>';
            }
            $detalle .= '</ul>';
        }
        
        if($this->authItemParents){    
            $detalle .= 'Es hijo de los roles/permisos: <ul>';
            foreach ($this->authItemParents as $authItemParent) {
                $detalle .= '<li>'.$authItemParent->parent.'</li>';
            }
            $detalle .= '</ul>';
        }
        
        if($this->authMenuItems){    
            $detalle .= 'Es requerido en los menús: <ul>';
            foreach ($this->authMenuItems as $authMenuItem) {
                $detalle .= '<li>'.$authMenuItem->name.'</li>';
            }
            $detalle .= '</ul>';
        }
        
        return $detalle;
    }
}

backend/controllers/AuthItemController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\AuthItem;
use backend\models\AuthItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Controlador que permite administrar el modelo AuthItem
 * 
 * El controlador permite realizar las siguientes acciones sobre el modelo AuthItem:
 * listar, crear, ver y eliminar
 * 
 * @since 1.0
 */
class AuthItemController extends Controller {
    /**
     * Leer documentación de Yii2
     * 
     * @link http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html
     * @return array
     */
    public function behaviors() {
        return [
           
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lista todos los modelos AuthItem
     * 
     * @return view la vista 'index'
     */
    public function actionIndex() {
        $searchModel = new AuthItemSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
        ]);
    }

    /**
     * Permite ver el detalle y actualizar el modelo AuthItem
     * 
     * Redirecciona siempre a la vista 'view'
     * 
     * @param string $id identificador único
     * @return mixed muestra la vista 'view' con los detalles
     */
    public function actionView($id) {
        $model = $this->findModel($id);
        $model->validate();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Rol/Permiso actualizado correctamente');
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('view', ['model' => $model]);
        }
    }

    /**
     * Crea un nuevo modelo AuthItem
     * 
     * Redirecciona a la vista 'view' si se creó correctamente
     * 
     * @return mixed retorna la vista 'view' si se creó; de lo contrario retorna
     * la vista 'create'
     */
    public function actionCreate() {
        $model = new AuthItem;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Rol/Permiso creado correctamente');
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('create', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Elimina un modelo AuthItem
     * 
     * Redirecciona siempre a la vista 'index' con un mensaje del estado de la eliminación
     * 
     * @param string $id identificador único
     * @return mixed redirecciona a la vista 'index'
     */
    public function actionDelete($id) {
        $model = $this->findModel($id);
    
        if($model->sePuedeEliminar()){
            $modelTmp = $model;
            $model->delete();
            Yii::$app->session->setFlash("success", 'Se eliminó el rol/permiso: '
                    . $modelTmp->name .' correctamente');
        } else {
            $detalle = $model->objetosRelacionados();
            Yii::$app->session->setFlash("error", $model->name." no se puede "
                    . "eliminar porque se encuentra relacionado con: <br/>". $detalle);
        }
        
        return $this->redirect(['index']);
    }

    /**
     * Busca un modelo AuthItem
     * 
     * La busqueda la hace basado en el valor de su llave primaria. Si el modelo 
     * no existe, se lanza una excepción HTTP 404.
     * 
     * @param string $id identificador único
     * @return AuthItem el modelo AuthItem
     * @throws NotFoundHttpException si el modelo no existe
     */
    protected function findModel($id) {
        if (($model = AuthItem::findOne($id)) !== NULL) {
            return $model;
        } else {
            throw new NotFoundHttpException('La página solicitada no existe');
        }
    }
}

backend/views/auth-item/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;

/**
 * @var yii\web\View $this
 * @var administracion\models\AuthItem $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="auth-item-form">

    <?php $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL]); echo Form::widget([

        'model' => $model,
        'form' => $form,
        'columns' => 1,
        'attributes' => [

            'name'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Rol/Permiso...', 'maxlength'=>64]],

            'type'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Tipo...']],
            
            'type' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => '\kartik\widgets\Select2',
                'options' => [
                    'data' => \backend\models\AuthItem::arrayTipo(),
                    'options' => ['placeholder' => 'Seleccionar...'],
                    'pluginOptions' => [
                        'allowClear' => TRUE
                    ],
                ],
            ],            
            'description'=>['type'=> Form::INPUT_TEXTAREA, 'options'=>['placeholder'=>'Enter Descripción...','rows'=> 6]],
        ]

    ]);

    echo Html::submitButton($model->isNewRecord ? 'Crear' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
    ActiveForm::end(); ?>

</div>

backend/views/auth-item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var administracion\models\AuthItemSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="auth-item-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'rule_name') ?>

    <?= $form->field($model, 'data') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/auth-item/create.php
<?php

use common\widgets\Titulo;

/**
 * @var yii\web\View $this
 * @var administracion\models\AuthItem $model
 */

$this->title = 'Crear rol o permiso';
$this->params['breadcrumbs'][] = 'Sistema';
$this->params['breadcrumbs'][] = 'Parametrización avanzada';
$this->params['breadcrumbs'][] = ['label' => 'Roles y permisos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-create">

    <?php
    echo Titulo::widget([
        'tipo' => Titulo::TIPO_PRINCIPAL,
        'titulo' => $this->title]); 
    
    echo $this->render('_form', [
            'model' => $model,
    ]); ?>

</div>

backend/views/auth-item/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use common\widgets\Titulo;
use backend\models\AuthItem;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var administracion\models\AuthItemSearch $searchModel
 */

$this->title = 'Roles y permisos';
$this->params['breadcrumbs'][] = 'Sistema';
$this->params['breadcrumbs'][] = 'Parametrización avanzada';
$this->params['breadcrumbs'][] = $this->title;

$botonCrear = Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
        ['class' => 'btn btn-success', 'title' => 'Crear']);

$contenido = [
    'content' => $botonCrear
        . Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], 
            ['class' => 'btn btn-default', 'title' => 'Restablecer vista'])
];

$columnaAcciones = [
    'class' => 'kartik\grid\ActionColumn',
    'template' => '{update}{delete}',
    'buttons' => [
        'update' => function ($url, $model) {
            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', 
                    Yii::$app->urlManager->createUrl(['auth-item/view','id' => $model->name,'edit'=>'t']), [
                'title' => Yii::t('yii', 'Edit'),
            ]);}
    ]
];
?>

<div>

<?php
    echo Titulo::widget([
        'tipo' => Titulo::TIPO_PRINCIPAL,
        'titulo' => $this->title,
    ]);

    $columnas = [
        'serial' => ['class'=>'kartik\grid\SerialColumn'],
        'nombre' => [
            'attribute' => 'name',
            'value' => 'name',
            'filter' => ArrayHelper::map(\backend\models\AuthItem::find()->all(), 'name', 'name'),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,

            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ],
        'tipo' => [
            'attribute' => 'type',
            'value' => 'tipoTexto',
            'filter' => AuthItem::arrayTipo(),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,
            'width' => "10%",

            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ],  

        $columnaAcciones,
    ];
            
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columnas,
        'bootstrap' => TRUE,
        'responsive' => TRUE,
        'hover' => TRUE,
        'condensed' => TRUE,
        'floatHeader' => TRUE,
        'resizableColumns' => TRUE,
        'panel' => [
            'heading' => '<h3 class="panel-title"></h3>',
            'type' => GridView::TYPE_PRIMARY,
        ],
        'toolbar' => [
            $contenido,
//            '{export}',
            '{toggleData}',
        ],
    ]);
    
    ?>
</div>

backend/views/auth-item/view.php
<?php

use kartik\detail\DetailView;
use common\widgets\Titulo;

/**
 * @var yii\web\View $this
 * @var administracion\models\AuthItem $model
 */

$this->title = $model->name;
$this->params['breadcrumbs'][] = 'Sistema';
$this->params['breadcrumbs'][] = 'Parametrización avanzada';
$this->params['breadcrumbs'][] = ['label' => 'Roles y permisos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-view">

    <?php
        echo Titulo::widget([
            'tipo' => Titulo::TIPO_PRINCIPAL,
            'titulo' => $this->title]); 
    ?>

    <?= DetailView::widget([
            'model' => $model,
            'condensed'=>FALSE,
            'hover'=>TRUE,
            'mode'=>Yii::$app->request->get('edit')=='t' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
            'panel'=>[
            'heading'=>$this->title,
            'type'=>DetailView::TYPE_PRIMARY,
        ],
        'attributes' => [
            'name',
            [
                'attribute' => 'type',
                'value' => $model->tipoTexto,
                'type' => DetailView::INPUT_SELECT2,
                'widgetOptions' => [
                    'data' => \backend\models\AuthItem::arrayTipo(),
                ],
            ],
        'description:ntext',
        ],
        'deleteOptions'=>[
            'url'=>['delete', 'id' => $model->name],
            'confirm'=>'Seguro que quiere borrar este Rol/Permiso y todo lo que depende de él',
        ],
        'enableEditMode'=>TRUE,
    ]) ?>

</div>