common/models/AuthMenuItem.php
<?php

namespace common\models;

use Yii;

/**
 * El modelo AuthMenuItem representa un item de menú o submenú
 * 
 * Ejemplo:
 * 
 * "Sistema" es un menú y "Parametrización básica" es un submenú
 *
 * @property int $id identificador único
 * @property int $padre padre
 * @property int $orden orden en que aparecerán las opciones
 * @property string $auth_item nombre del rol/permiso
 * @property string $name nombre del menú
 * @property string $label etiqueta
 * @property string $ruta ruta a donde lleva el menú
 * @property string $icono icono que se ve al lado del menú
 * @property int $separador ¿Incluye separador después del item?
 * @property string $tipo ¿A cuál aplicación pertenece?
 * @property string $visible si es visible para el usuario
 * @property string $descripcion descripción
 * @property int $creado_por creado por
 * @property datetime $creado_el creado el
 * @property int $actualizado_por actualizado por
 * @property datetime $actualizado_el actualizado el
 *
 * @property AuthItem $authItem permiso
 * @property AuthMenuItem $menuPadre menú padre
 * 
 * @author Brian Cardona Salazar <brian.cardonas@autonoma.edu.co>
 * @author Lina María Ocampo Cuartas <lina.ocampo@autonoma.edu.co>
 */
class AuthMenuItem extends MyActiveRecord {
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'auth_menu_item';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['padre', 'orden', 'visible', 'separador'], 'integer'],
            [['auth_item', 'name', 'label', 'tipo', 'ruta', 'visible'], 'required'],
            [['tipo', 'descripcion'], 'string'],
            [['auth_item'], 'string', 'max' => 64],
            [['name'], 'string', 'max' => 40],
            [['label'], 'string', 'max' => 60],
            [['ruta', 'icono'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['padre'], 'sonIguales'],
            [['tipo', 'descripcion', 'auth_item', 'name', 'label', 'ruta', 'icono'], 'filter', 'filter' => 'trim'],
        ];
    }
    
    /**
     * ¿Son iguales?
     * 
     * Permite saber si la relación que se está creando tiene el mismo
     * menú como padre y como hijo; lo cuál, no es válido
     * 
     * @param type $attribute
     * @param type $params
     */
    public function sonIguales($attribute, $params) {
        if($this->id == $this->padre){
            $this->addError($attribute, "El padre y el hijo no pueden ser el mismo");
        } 
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'padre' => 'Padre',
            'orden' => 'Orden',
            'auth_item' => 'Permiso',
            'name' => 'Nombre',
            'label' => 'Etiqueta',
            'ruta' => 'Ruta',
            'icono' => 'Icono',
            'separador' => '¿Separador?',
            'tipo' => 'Tipo',
            'visible' => 'Visible',
            'descripcion' => 'Descripción',
            'creado_por' => 'Creado por',
            'creado_el' => 'Creado el',
            'actualizado_por' => 'Actualizado por',
            'actualizado_el' => 'Actualizado el',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItem() {
        return $this->hasOne(\backend\models\AuthItem::className(), ['name' => 'auth_item']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuPadre() {
        return $this->hasOne(AuthMenuItem::className(), ['id' => 'padre']);
    }

    /**
     * Crea el menú de forma dinámica utilizando la información
     * de la base de datos
     * 
     * @param string $padre rama desde la cual se comienza a armar el menú
     * @param string $tipo puede ser 'administracion' o 'aplicacion'
     * @return array arreglo con todas las opciones del menú
     */
    public static function crearMenu($padre, $tipo){
        $menuPadre = AuthMenuItem::find()->where('id = :id', [':id' => $padre])->one();
        $hijos = self::find()
                ->where('padre = :padre', [':padre' => $padre])
                ->andWhere('tipo = :tipo', [':tipo' => $tipo])
                ->orderBy('orden')
                ->all();        
        
        if($hijos){
            $items = [];
            foreach ($hijos as $key => $hijo) {
                $items[] = self::crearMenu($hijo->id, $tipo);
                if($hijo->separador) {
                    $items[] = '<li class="divider"></li>';
                }
            }
            
            return [ //rama
                    'label' => "<span class='$menuPadre->icono' aria-hidden='true'></span> $menuPadre->label",
                    'url' => [$menuPadre->ruta],
                    'visible' => Yii::$app->user->can($menuPadre->auth_item)
                            && $menuPadre->visible,
                    'items' => $items,
                ];           
                
        } else {
            return //hoja;
                [ 
                    'label' => "<span class='$menuPadre->icono' aria-hidden='true'></span> $menuPadre->label",
                    'url' => [$menuPadre->ruta],
                    'visible' => Yii::$app->user->can($menuPadre->auth_item)
                            && $menuPadre->visible,
                ];
        }
    }
    
    /**
     * Crea una lista jerárquica con las opciones del menú sin considerar
     * los permisos
     * 
     * @param string $padre rama desde la cual se comienza a armar el menú
     * @param string $tipo puede ser 'administracion' o 'aplicacion'
     * @return array arreglo con todas las opciones del menú
     */
    public static function analisisMenu($padre, $tipo){
        
        $padreObj = AuthMenuItem::find()->where('id = :id', [':id' => $padre])->one();
        $hijos = self::find()
                    ->where('padre = :padre', [':padre' => $padre])
                    ->andWhere('tipo = :tipo', [':tipo' => $tipo])
                    ->orderBy('orden')
                    ->all();
        
        if($hijos){
            
            $nodes = [];
            foreach ($hijos as $key => $hijo) {
                $nodes[] = self::analisisMenu($hijo->id, $tipo);
            }
            
            return [ //rama 
                    'text' => "[$padreObj->name - "
                    . "<span class='$padreObj->icono' aria-hidden='true'></span>"
                    . "$padreObj->label] - [$padreObj->ruta] - [$padreObj->auth_item]" , 
                    'nodes' => $nodes,
                ];           
                
        } else {
            return //hoja;
                [ 
                    'text' => "[$padreObj->name - "
                    . "<span class='$padreObj->icono' aria-hidden='true'></span>"
                    . "$padreObj->label] - [$padreObj->ruta] - [$padreObj->auth_item]" , 
                ];
        }
    }    
}

backend/controllers/AuthMenuItemController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\AuthMenuItem;
use backend\models\AuthMenuItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Controlador que permite administrar el modelo AuthMenuItem
 * 
 * El controlador permite realizar las siguientes acciones sobre el modelo AuthMenuItem:
 * listar, crear, ver y eliminar
 * 
 * @since 1.0
 */
class AuthMenuItemController extends Controller {
    /**
     * Leer documentación de Yii2
     * 
     * @link http://www.yiiframework.com/doc-2.0/guide-concept-behaviors.html
     * @return array
     */
    public function behaviors() {
        return [
                    
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lista todos los modelos AuthMenuItem
     * 
     * @return view la vista 'index'
     */
    public function actionIndex() {
        $searchModel = new AuthMenuItemSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
        ]);
    }

    /**
     * Permite ver el detalle y actualizar el modelo AuthMenuItem
     * 
     * Redirecciona siempre a la vista 'view'
     * 
     * @param string $id identificador único
     * @return mixed muestra la vista 'view' con los detalles
     */
    public function actionView($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Menú actualizado correctamente');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('view', ['model' => $model]);
        }
    }

    /**
     * Crea un nuevo modelo AuthMenuItem
     * 
     * Redirecciona a la vista 'view' si se creó correctamente
     * 
     * @return mixed retorna la vista 'view' si se creó; de lo contrario retorna
     * la vista 'create'
     */
    public function actionCreate() {
        $model = new AuthMenuItem;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Menú creado correctamente');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                    'model' => $model,
            ]);
        }
    }

    /**
     * Elimina un modelo AuthMenuItem
     * 
     * Redirecciona siempre a la vista 'index' con un mensaje del estado de la eliminación
     * 
     * @param int $id identificador único
     * @return mixed redirecciona a la vista 'index'
     */
    public function actionDelete($id) {
        $model = $this->findModel($id);
        $modelTmp = $model;
        
        if($model->delete()){
            Yii::$app->session->setFlash("success", 'Se eliminó el menú: '
                    . $modelTmp->name .' correctamente');
        } else {
            Yii::$app->session->setFlash("error", 'Problema al eliminar el menú');
        }
        
        return $this->redirect(['index']);
    }
    
    /**
     * Busca un modelo AuthMenuItem
     * 
     * La busqueda la hace basado en el valor de su llave primaria. Si el modelo 
     * no existe, se lanza una excepción HTTP 404.
     * 
     * @param int $id identificador único
     * @return AuthMenuItem el modelo AuthMenuItem
     * @throws NotFoundHttpException si el modelo no existe
     */
    protected function findModel($id) {
        if (($model = AuthMenuItem::findOne($id)) !== NULL) {
            return $model;
        } else {
            throw new NotFoundHttpException('La página solicitada no existe');
        }
    }
}

backend/views/auth-menu-item/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use yii\helpers\ArrayHelper;
use common\models\AuthMenuItem;
use backend\models\AuthItem;

/**
 * @var yii\web\View $this
 * @var common\models\AuthMenuItem $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="auth-menu-item-form">

    <?php $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL]); echo Form::widget([

        'model' => $model,
        'form' => $form,
        'columns' => 1,
        'attributes' => [

            'name'=>['type'=> Form::INPUT_TEXT, 'options'=> [
                'placeholder'=>'Enter Nombre del item...', 'maxlength'=>40]],
            
            'label'=>['type'=> Form::INPUT_TEXT, 'options'=>[
                'placeholder'=>'Enter Texto que verá el usuario...', 'maxlength'=>60]],

            'auth_item' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => '\kartik\widgets\Select2',
                'options' => [
                    'data' => ArrayHelper::map(AuthItem::find()->all(), 'name', 'name'),
                    'options' => ['placeholder' => 'Seleccionar...'],
                    'pluginOptions' => [
                        'allowClear' => TRUE
                    ],
                ],
            ],

            'tipo' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => '\kartik\widgets\Select2',
                'options' => [
                    'data' => Yii::$app->ayudante
                                    ->datosEnum(AuthMenuItem::tableName(), 'tipo'),
                    'options' => ['placeholder' => 'Seleccionar...'],
                    'pluginOptions' => [
                        'allowClear' => TRUE
                    ],
                ],
            ],
            
            'separador' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => '\kartik\widgets\Select2',
                'options' => [
                    'data' => Yii::$app->ayudante->booleanArray(),
                    'options' => ['placeholder' => 'Seleccionar...'],
                    'pluginOptions' => [
                        'allowClear' => TRUE
                    ],
                ],
            ],
            
            'padre' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => '\kartik\widgets\Select2',
                'options' => [
                    'data' => ArrayHelper::map(AuthMenuItem::find()->all(), 'id', 'name'),
                    'options' => ['placeholder' => 'Seleccionar...'],
                    'pluginOptions' => [
                        'allowClear' => TRUE
                    ],
                ],
            ],
            
            'visible' => [
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => '\kartik\widgets\Select2',
                'options' => [
                    'data' => Yii::$app->ayudante->booleanArray(),
                    'options' => ['placeholder' => 'Seleccionar...'],
                    'pluginOptions' => [
                        'allowClear' => TRUE
                    ],
                ],
            ],

            'orden'=>['type'=> Form::INPUT_TEXT, 'options'=>[
                'placeholder'=>'Enter Orden en que aparecerán las opciones...']],

            'ruta'=>['type'=> Form::INPUT_TEXT, 'options'=>[
                'placeholder'=>'Enter Ruta a la cual lleva el menú...', 'maxlength'=>200]],

            'icono'=>['type'=> Form::INPUT_TEXT, 'options'=>[
                'placeholder'=>'Enter Icono que se verá al lado del menú...', 'maxlength'=>30]],

            'descripcion'=>['type'=> Form::INPUT_TEXTAREA, 'options'=>[
                'placeholder'=>'Enter Descripción...','rows'=> 6]],

        ]

    ]);

    echo Html::submitButton($model->isNewRecord ? 'Crear' : 'Actualizar', [
        'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
    ActiveForm::end(); ?>

</div>

backend/views/auth-menu-item/create.php
<?php

use common\widgets\Titulo;

/**
 * @var yii\web\View $this
 * @var common\models\AuthMenuItem $model
 */

$this->title = 'Crear menú';
$this->params['breadcrumbs'][] = 'Sistema';
$this->params['breadcrumbs'][] = 'Parametrización avanzada';
$this->params['breadcrumbs'][] = ['label' => 'Menús', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-menu-item-create">

    <?php
        echo Titulo::widget([
            'tipo' => Titulo::TIPO_PRINCIPAL,
            'titulo' => $this->title]); ?>
    
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/auth-menu-item/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use common\widgets\Titulo;
use common\components\Ayudante;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var administracion\models\AuthMenuItemSearch $searchModel
 */

$this->title = 'Menús';
$this->params['breadcrumbs'][] = 'Sistema';
$this->params['breadcrumbs'][] = 'Parametrización avanzada';
$this->params['breadcrumbs'][] = $this->title;

$botonCrear = Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
        ['class' => 'btn btn-success', 'title' => 'Crear']);

$contenido = [
    'content' => $botonCrear
        . Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], 
            ['class' => 'btn btn-default', 'title' => 'Restablecer vista'])
];

$columnaAcciones = [
    'class' => 'kartik\grid\ActionColumn',
    'template' => '{update}{delete}',
    'buttons' => [
        'update' => function ($url, $model) {
            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', 
                Yii::$app->urlManager->createUrl(['auth-menu-item/view','id' => $model->id,'edit'=>'t']), [
                    'title' => 'editar',
                ]);
        }
    ],
];
?>

<div>

<?php
    echo Titulo::widget([
        'tipo' => Titulo::TIPO_PRINCIPAL,
        'titulo' => $this->title,
    ]);

    $columnas = [
        'serial' => ['class'=>'kartik\grid\SerialColumn'],
        'padre' => [
            'attribute' => 'padre',
            'value' => 'menuPadre.name',
            'filter' => ArrayHelper::map(common\models\AuthMenuItem::find()->all(), 'id', 'name'),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,

            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ],
        'nombre' => [
            'attribute' => 'name',
            'vAlign' => GridView::ALIGN_MIDDLE,
        ],
        'etiqueta' => [
            'attribute' => 'label',
            'vAlign' => GridView::ALIGN_MIDDLE,
        ],
        'permiso' => [
            'attribute' => 'auth_item',
            'value' => 'authItem.name',
            'filter' => ArrayHelper::map(\backend\models\AuthItem::find()->all(), 'name', 'name'),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,

            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ], 
        'tipo' => [
            'attribute' => 'tipo',
            'value' => 'tipo',
            'filter' => Yii::$app->ayudante->datosEnum('auth_menu_item', 'tipo'),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,
            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ],
        'separador' => [
            'attribute' => 'separador',
            'value'=> function($model) {
                return Ayudante::booleanArray()[$model->separador];
            },
            'filter' => Yii::$app->ayudante->booleanArray(),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,
            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ],
        'visible' => [
            'attribute' => 'visible',
            'value'=> function($model) {
                return Ayudante::booleanArray()[$model->visible];
            },
            'filter' => Yii::$app->ayudante->booleanArray(),
            'class' => '\kartik\grid\DataColumn',
            'vAlign' => GridView::ALIGN_MIDDLE,
            'filterType' => GridView::FILTER_SELECT2,
            'filterWidgetOptions' => [
                'options' => ['placeholder' => 'Seleccionar...'],
                'pluginOptions' => [
                    'allowClear' => TRUE
                ],
            ],
        ],

        $columnaAcciones,
    ];
            
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columnas,
        'bootstrap' => TRUE,
        'responsive' => TRUE,
        'hover' => TRUE,
        'condensed' => TRUE,
        'floatHeader' => TRUE,
        'resizableColumns' => TRUE,
        'panel' => [
            'heading' => '<h3 class="panel-title"></h3>',
            'type' => GridView::TYPE_PRIMARY,
        ],
        'toolbar' => [
            $contenido,
//            '{export}',
            '{toggleData}',
        ],
    ]);
    
?>
</div>

backend/views/auth-menu-item/view.php
<?php

use kartik\detail\DetailView;
use yii\helpers\ArrayHelper;
use common\widgets\Titulo;
use backend\models\AuthItem;
use common\models\AuthMenuItem;

/**
 * @var yii\web\View $this
 * @var common\models\AuthMenuItem $model
 */

$this->title = $model->name;
$this->params['breadcrumbs'][] = 'Sistema';
$this->params['breadcrumbs'][] = 'Parametrización avanzada';
$this->params['breadcrumbs'][] = ['label' => 'Menús', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-menu-item-view">

    <?php 
    echo Titulo::widget([
        'tipo' => Titulo::TIPO_PRINCIPAL,
        'titulo' => $this->title]); 
    ?>

    <?= DetailView::widget([
            'model' => $model,
            'condensed'=>FALSE,
            'hover'=>TRUE,
            'mode'=>Yii::$app->request->get('edit')=='t' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
            'panel'=>[
            'heading'=>$this->title,
            'type'=>DetailView::TYPE_PRIMARY,
        ],
        'attributes' => [
            'name',
            'label',

            [
                'attribute' => 'auth_item',
                'value' => $model->auth_item,
                'type' => DetailView::INPUT_SELECT2,
                'widgetOptions' => [
                    'data' => ArrayHelper::map(AuthItem::find()->orderBy('name')
                                ->asArray()->all(), 'name', 'name'),
                ],
            ],            
            
            [
                'attribute' => 'tipo',
                'value' => $model->tipo,
                'type' => DetailView::INPUT_SELECT2,
                'widgetOptions' => [
                    'data' => Yii::$app->ayudante->datosEnum('auth_menu_item', 'tipo'),
                ],
            ],
            
            [
                'attribute' => 'visible',
                'value' => $model->visible ? "Si" : "No",
                'type' => DetailView::INPUT_SELECT2,
                'widgetOptions' => [
                    'data' => Yii::$app->ayudante->booleanArray(),
                ],
            ],            
            
            [
                'attribute' => 'padre',
                'value' => $model->menuPadre->name,
                'type' => DetailView::INPUT_SELECT2,
                'widgetOptions' => [
                    'data' => ArrayHelper::map(AuthMenuItem::find()->orderBy('name')
                                ->asArray()->all(), 'id', 'name'),
                ],
            ],            
            
            'orden',
            'ruta',
            'icono',
            
            [
                'attribute' => 'separador',
                'value' => $model->separador ? "Si" : "No",
                'type' => DetailView::INPUT_SELECT2,
                'widgetOptions' => [
                    'data' => Yii::$app->ayudante->booleanArray(),
                ],
            ], 
            
            'descripcion:ntext',
        ],
        'deleteOptions'=>[
            'url'=>['delete', 'id' => $model->id],
            'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?'),
            'data'=>[
                'method'=>'post',
            ],
        ],
        'enableEditMode'=>TRUE,
    ]) ?>

</div>